# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  LOCATION: westus2
  RESOURCE_GROUP_NAME: Solution-Speech-Bot-Demo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: Azure/login@73efa77
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-PSSession: true

    - name: Run a one-line script
      run: . .\Deploy-Template.ps1 -Location $env:LOCATION -ResourceGroupName $env:RESOURCE_GROUP_NAME
      shell: pwsh
