# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  LOCATION: westus2
  RESOURCE_GROUP_NAME: Solution-Speech-Bot-Demo
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Deploy to Azure
      shell: pwsh
      run: |
        $cred = $env:AZURE_CREDENTIALS | ConvertFrom-Json
        $secret = ConvertTo-SecureString $cred.clientSecret -AsPlainText -Force
        
